baseURL = "https://s4kmedia.github.io/nba-eurozone/"
title = "NBA EuroZone"
publishDir = "public"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true
canonifyURLs = true

# âœ… local theme
theme = "ananke"

# ÎµÏ€Î¹Ï„ÏÎ­Ï€ÎµÎ¹ raw HTML ÏƒÎµ Ï€ÎµÏÎ¹ÎµÏ‡ÏŒÎ¼ÎµÎ½Î¿
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  # Î’Î³Î¬Î»Î±Î¼Îµ Ï„Î¿ "JSON" Î³Î¹Î± Î½Î± Î¼Î·Î½ Î³ÏÎ¬Ï†ÎµÎ¹ warn. Î‘Î½ Ï„Î¿ Ï‡ÏÎµÎ¹Î±ÏƒÏ„ÎµÎ¯Ï‚ Î¾Î±Î½Î¬, Ï„Î¿ Î¾Î±Î½Î±Î²Î¬Î¶Î¿Ï…Î¼Îµ.
  home = ["HTML", "RSS"]

[pagination]
  pagerSize = 12

[taxonomies]
  tag = "tags"
  category = "categories"
  player = "players"
  team = "teams"
  league = "leagues"
  country = "countries"
  topic = "topics"

[permalinks]
  posts = "/:slug/"

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  show_reading_time = true
  recent_posts_number = 12
  background_color_class = "bg-black"
  cover_dimming_class = "bg-black-60"
  mainSections = ["posts"]   # ğŸ‘ˆ ÎšÎ»ÎµÎ¹Î´Î¯: Î´ÎµÎ¯Î¾Îµ Ï„Î¿ section "posts" ÏƒÏ„Î·Î½ Î±ÏÏ‡Î¹ÎºÎ®

[languages]

  [languages.en]
    languageName = "EN"
    weight = 1
    title = "NBA EuroZone"
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "News"
        url  = "/"
        weight = 1
      [[languages.en.menu.main]]
        name = "Categories"
        url  = "/categories/"
        weight = 2
      [[languages.en.menu.main]]
        name = "Tags"
        url  = "/tags/"
        weight = 3
      [[languages.en.menu.main]]
        name = "About"
        url  = "/about/"
        weight = 5

  [languages.el]
    languageName = "EL"
    weight = 2
    title = "NBA EuroZone"
    contentDir = "content/el"
    [languages.el.menu]
      [[languages.el.menu.main]]
        name = "ÎÎ­Î±"
        url  = "/"
        weight = 1
      [[languages.el.menu.main]]
        name = "ÎšÎ±Ï„Î·Î³Î¿ÏÎ¯ÎµÏ‚"
        url  = "/categories/"
        weight = 2
      [[languages.el.menu.main]]
        name = "Î•Ï„Î¹ÎºÎ­Ï„ÎµÏ‚"
        url  = "/tags/"
        weight = 3
      [[languages.el.menu.main]]
        name = "Î£Ï‡ÎµÏ„Î¹ÎºÎ¬"
        url  = "/about/"
        weight = 5
